from typing import Protocol

from infraprobe.models import Job, JobStatus, ScanRequest, ScanResponse


class JobStore(Protocol):
    async def create(self, job_id: str, request: ScanRequest) -> Job: ...

    async def get(self, job_id: str) -> Job | None: ...

    async def update_status(self, job_id: str, status: JobStatus) -> None: ...

    async def complete(self, job_id: str, result: ScanResponse) -> None: ...

    async def fail(self, job_id: str, error: str) -> None: ...
